### ISSUE TITLE
Read Netlify arguments from environment variable

### ISSUE THREAD

**Issue by zack9433** [ngx-builders/netlify-builder#22]
**Is your feature request related to a problem? Please describe.**

I think `netlifyToken` and `siteId` should not commit into VCS because someone could see the token.

**Describe the solution you'd like**

Using environment variable instead of setting in angular.json.

**Comment by santoshyadav198613** [comment]
Hi @zack9433 ,
Thanks for the issue, we will work on it.

**Comment by santoshyadav198613** [comment]
Hi @zack9433 ,
It is released with 2.0.0.
