### ISSUE TITLE
Implement implementation to verify if site exist if not create one

### ISSUE THREAD

**Issue by santoshyadav198613** [ngx-builders/netlify-builder#3]
Netlify API provides the Methods to create site and retrieve list of sites.

const NetlifyAPI = require('netlify')
const client = new NetlifyAPI('1234myAccessToken') -- API to be provide via config or while deployment
 
// Fetch sites
const sites = await client.listSites()
 
// Create a site. Notice `body` here for sending OpenAPI body
const site = await netlify.createSite({
  body: {
    name: `my-awesome-site`
    // ... https://open-api.netlify.com/#/default/createSite
  }
})

Create site if siteId does not exist. use existing if it exist.

**Comment by imranmomin** [comment]
create pr #71
