### ISSUE TITLE
Support to read configuration parameter from environment variable 

### ISSUE THREAD

**Issue by zack9433** [ngx-builders/netlify-builder#31]
**Is your feature request related to a problem? Please describe.**

In my scenario, I have a stage and production environment and stage is for preview purpose and stage have its own build configuration.

**Describe the solution you'd like**

Let CI decides to build for stage or production by an environment variable.

**Comment by santoshyadav198613** [comment]
The feature is added, just needs to be documented. I will update post verification.

**Comment by santoshyadav198613** [comment]
https://github.com/ngx-builders/netlify-builder/pull/34 will close this.

**Comment by santoshyadav198613** [comment]
This is closed, please let us know if you have any questions.
