### ISSUE TITLE
Align options with RFC 1 of ngx-deploy-starter

### ISSUE THREAD

**Issue by JohannesHoppe** [ngx-builders/netlify-builder#33]
I have started a discussion [at ngx-deploy-starter RFC #1](https://github.com/angular-schule/ngx-deploy-starter/issues/1) about a standardised set of options. It would be great if we could find a common approach so that the expected behaviour and usability of the different builders are consistent.

Currently, there could be a majority for the following options:
- `--configuration` (alias `-c`): A named build target, as specified in the "configurations" section of angular.json
- `--no-build`: Skip build process during deployment

Right now for netlify-builder only `--configuration` is supported, the alias is missing as well as the `--no-build` option.

Additionally, https://github.com/ngx-builders/netlify-builder/blob/master/command-builder/deploy/schema.json could be fixed.

**Comment by santoshyadav198613** [comment]
Thanks @JohannesHoppe ,

Will work on it.
