### ISSUE TITLE
Add the videos and blog post  from Tara to docs

### ISSUE THREAD

**Issue by santoshyadav198613** [ngx-builders/netlify-builder#37]
Videos:
https://youtu.be/tILx6ylyP_4 
https://youtu.be/yHETIuM391E 
https://youtu.be/yHETIuM391E

Blog post:
https://www.netlify.com/blog/2019/09/17/using-the-angular-builder-for-netlify/

**Comment by Shaikh-Ubaid** [comment]
I am working on it. Please assign it to me.

**Comment by santoshyadav198613** [comment]
closed via https://github.com/ngx-builders/netlify-builder/pull/39
