### ISSUE TITLE
align app structure to ngx-deploy-starter

### ISSUE THREAD

**Issue by santoshyadav198613** [ngx-builders/netlify-builder#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The application structure is not aligned to ngx-deploy-starter
**Describe alternatives you've considered**
NA
**Additional context**
refer https://github.com/angular-schule/ngx-deploy-starter for structure

**Comment by JohannesHoppe** [comment]
FYI, I aligned more parts with the very first deploy builder (@angular/fire)

**Keeping track of all the forks:**

[ngx-deploy-starter](https://github.com/angular-schule/ngx-deploy-starter/) and [angular-cli-ghpages](https://github.com/angular-schule/angular-cli-ghpages/) are follow-up projects of the deprecated [ngx-gh demo](https://github.com/mgechev/ngx-gh).
This project was a follow-up of the deploy schematics from the [angularfire](https://github.com/angular/angularfire/) project.

😅
