### ISSUE TITLE
Improvement: Environment config values should not be part of angular.json

### ISSUE THREAD

**Issue by NileshPatel17** [ngx-builders/netlify-builder#52]
Improvement: Environment config values should not be part of angular.json specially if these are sensitive.

Recommendation:
should be move to src/environment/environment*.json

Please let me know what do you think.
** This is not an bug or feature :)

**Comment by santoshyadav198613** [comment]
You can refer https://www.netlify.com/blog/2019/09/17/using-the-angular-builder-for-netlify/

**Comment by santoshyadav198613** [comment]
As explained in blog post, you can use environment variable as well.
